var blockedCommands = [ 
  'Restore Defaults',
  //'Get More Themes',
  //'Manage',
  //'Title Bar',
  //'Learn more…',
  //'Bookmarks Toolbar Items',
  //'About Firefox',
  //'This isn\'t a web forgery…',
  //'Report Web Forgery…',
  //'Restart with Add-ons Disabled…',
  //'Submit Feedback…',
  //'Troubleshooting Information',
  //'Firefox Health Report',
  //'Keyboard Shortcuts',
  //'Firefox Tour',
  //'Firefox Help',
  'rdf:http://home.netscape.com/NC-rdf#Name',
  //'Preferences…',
  //'Get More Tools',
  //'Connect…',
  //'Error Console',
  //'Page Source',
  //'Scratchpad',
  //'Eyedropper',
  //'Responsive Design View',
  //'Browser Console',
  //'Browser Content Toolbox',
  //'Browser Toolbox',
  //'WebIDE',
  //'Developer Toolbar',
  //'Toggle Tools',
  //'Reconnect to Sync…',
  //'Sync Now',
  //'Sign In To Sync…',
  //'Start a conversation…',
  //'Subscribe to This Page…',
  //'Enter Full Screen',
  //'Text Encoding',
  //'Basic Page Style',
  //'No Style',
  //'History',
  //'Bookmarks',
  //'Work Offline',
  'Don\'t ask me again',
  'Not now',
  //'More Information',
  //'Disable protection for now',
  //'Enable protection',
  //'Disable protection for this session',
  //'Disable protection for this site',
  'Thanks!',
  'Add to Menu',
  'Add to Toolbar',
  'Remove from Menu',
  'Move to Toolbar',
  //'Unsorted Bookmarks',
  //'Bookmarks Toolbar',
  //'View Bookmarks Toolbar',
  //'View Bookmarks Sidebar',
  //'View Pocket List',
  //'Tabs From Other Devices',
  //'View History Sidebar',
  //'Help',
  //'Customize',
  'Open All in Tabs',
  'Learn more about DRM…',
  //'Inspect Element',
  //'View Saved Logins',
  //'Switch Page Direction',
  'Add Dictionaries…',
  //'Check Spelling',
  //'View Page Info',
  //'View Page Source',
  'View MathML Source',
  'View Selection Source',
  'View Frame Info',
  'View Frame Source',
  'Print Frame…',
  'Save Frame As…',
  'Bookmark This Frame',
  'Reload Frame',
  'Open Frame in New Window',
  'Open Frame in New Tab',
  'Show Only This Frame',
  'Share Selection',
  'Add a Keyword for this Search…',
  'View Background Image',
  //'Save Page to Pocket',
  //'Share This Page',
  'Hide this plugin',
  'Activate this plugin',
  'Email Audio…',
  'Email Video…',
  'Save Snapshot As…',
  'Save Audio As…',
  'Share This Video',
  'Save Video As…',
  'View Description',
  'View Image Info',
  'Set As Desktop Background…',
  'Email Image…',
  'Share This Image',
  'Save Image As…',
  'Copy Audio Location',
  'Copy Video Location',
  'Copy Image Location',
  'Copy Image',
  'View Video',
  //'View Image',
  //'Reload Image',
  //'Exit Full Screen',
  //'Full Screen',
  //'Hide Statistics',
  //'Show Statistics',
  //'Hide Controls',
  //'Show Controls',
  //'Ludicrous Speed (2×)',
  //'High Speed (1.5×)',
  //'Normal Speed',
  //'Slow Motion (0.5×)',
  //'Unmute',
  //'Mute',
  //'Pause',
  //'Play',
  'Copy Link Location',
  'Copy Email Address',
  'Save Link to Pocket',
  'Save Link As…',
  'Share This Link',
  'Bookmark This Link',
  'Open Link in New Private Window',
  'Open Link in New Window',
  'Open Link in New Tab',
  'Open Link',
  'Undo Add To Dictionary',
  'Add to Dictionary',
  'Exit Full Screen Mode',
  'Hide Toolbars',
  'Edit Pop-up Blocker Preferences…',
  'Remove from Toolbar',
  'Move to Menu',
  'Kill Web Process',
  'Kill Plugin',
  'Debug Script',
  'Stop Script',
  'Done',
  'Cancel',
  //'Undo Close Tab',
  //'Close Other Tabs',
  //'Close Tabs to the Right',
  //'Reload All Tabs',
  'Move to New Window',
  'New Group',
  //'Unpin Tab',
  //'Pin Tab',
  //'Reload Tab',
  //'Delete This Page',
  //'Bookmark This Page…',
  //'Forget About This Site',
  'Sort By Name',
  'Reload Live Bookmark',
  'Properties',
  'New Separator',
  'New Folder…',
  'New Bookmark…',
  'Open in a New Tab',
  'Open in a New Private Window',
  'Open in a New Window',
  'Open',
  //'Show All History',
  //'Show All Bookmarks',
  //'Manage Services…',
  //'Show desktop notifications',
  //'Show sidebar',
  //'New Private Window',
  //'Clear Recent History…',
  //'Add-ons',
  //'Downloads',
  'Shopping',
  'Banking',
  'Work',
  'Personal',
  'Restore Previous Session',
  //'Zoom Text Only',
  //'Reset',
  //'Zoom In',
  //'Zoom Out',
  //'Tab Groups',
  //'Show All Tabs',
  //'Forward',
  //'Back',
  //'Bookmark All Tabs…',
  //'Bookmark This Page',
  'Find Again',
  'Find',
  //'Page Info',
  //'Switch Text Direction',
  'Select All',
  'Delete',
  'Paste',
  'Copy',
  'Cut',
  'Redo',
  'Undo',
  //'Quit Firefox',
  'Add More Items…',
  //'Customize…',
  //'Close Window',
  //'Close Tab',
  //'Print…',
  //'Page Setup…',
  //'Email Link…',
  //'Save Page As…',
  //'Open File…',
  //'New Tab',
  //'New Window'
];

exports.blockedCommands = blockedCommands;
